config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "blog_posts" => "blog_posts#index", as: "all_posts"
  get "blog_posts/new" => "blog_posts#new", as: "new_blog_post"
  get "blog_posts/:id" => "blog_posts#show", as: "blog_post"
  post "blog_posts" => "blog_posts#create"
  delete "blog_posts/:id" => "blog_posts#delete", as: "delete_blog_post"
  root to: 'blog_posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog_post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @posts = BlogPost.all
    #render "index.html.erb"
  end

  def show
    @post = BlogPost.find(params[:id])
    #render "show.html.erb"
  end

  def create
    @post = BlogPost.new(sexy_params)
    if @post.save
      redirect_to @post
    else
      render action: :new
    end
  end

  def sexy_params
    params.require(:blog_post).permit([:title,:content])
  end

  def new
      @post = BlogPost.new
      # render "new.html.erb"
  end

  def delete
    @post = BlogPost.find(params[:id])
    if @post.destroy
      redirect_to all_posts_path
    else
      redirect_to blog_post_path(@post)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/index.html.erb
<h1>Blog Posts</h1>
<div>
    <%= link_to "Create New Entry", new_blog_post_path %>
</div>
<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, blog_post_path(post) %>
    </li>
  <% end %>
</ul>

app/views/blog_posts/new.html.erb
<h1>Add a Blog Post</h1>

<%= form_with model: @post, local: true do |form| %>
    <% if @post.errors.any? %>
        <div style="background-color:red">
            <h2>There is a problem officer, please resumbit</h2>
            <ul>
                <% @post.errors.full_messages.each do |error| %>
                    <li><%= error %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <%= form.label :title%>
    <%= form.text_field :title%>

    <br />
    <%= form.label :content %>
    <%= form.text_area :content %>

    <br />
    <%= form.submit :create %>
<% end %>

app/views/blog_posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>

<div>
  <%= link_to "All Posts", all_posts_path %>
</div>

<ul>
  <% @post.comments.each do |comment| %>
    <li>
      <%= comment.content %> :: by - <%= comment.author_name %>
    </li>
  <% end %>
</ul>

<%= link_to "Delete", delete_blog_post_path(@post), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>